# Generated by Django 4.2 on 2025-04-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chatroom_id',
            new_name='chatroom',
        ),
    ]
