# Generated by Django 3.2 on 2025-03-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='Industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
